services:
    one_signal_api.guzzle:
        class: GuzzleHttp\Client

    one_signal_api.guzzle_message_factory:
        class: Http\Message\MessageFactory\GuzzleMessageFactory

    one_signal_api.guzzle_adapter:
        class: Http\Adapter\Guzzle6\Client
        arguments:
            - '@one_signal_api.guzzle'

    one_signal_api.http_client:
        class: Http\Client\Common\HttpMethodsClient
        arguments:
            - '@one_signal_api.guzzle_adapter'
            - '@one_signal_api.guzzle_message_factory'

    one_signal_api.config:
        class: OneSignal\Config
        calls:
            - [setApplicationId, ['%one_signal_api.app_id%']]
            - [setApplicationAuthKey, ['%one_signal_api.app_auth_key%']]
            - [setUserAuthKey, ['%one_signal_api.user_auth_key%']]

    one_signal_api.service:
        class: OneSignal\OneSignal
        arguments:
            - '@one_signal_api.config'
            - '@one_signal_api.http_client'
